application: wave-france
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /index
  static_dir: index  
- url: /
  static_files: index/index.html
  upload: index/index.html 
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico